### ISSUE TITLE
alternative to the use of `globals()`?

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo-plugins-sensorsearch#1]
I see that there are 2 lines where `globals()` is used, https://github.com/search?q=repo%3Ardmorganiser%2Frdmo-plugins-sensorsearch%20globals&type=code, this is generally not recommended (and also considered a code smell https://python3.info/devops/quality/code-smells.html ;) )

 Can you not use instead a dict mapping as a  registry like so?
 
 ```py
PROVIDER_REGISTRY = {
    "O2ARegistrySearchProvider": O2ARegistrySearchProvider,
    "SensorManagementSystemProvider": SensorManagentSystemProvider,
    "GeophysicalInstrumentPoolPotsdamProvider": GeophysicalInstrumentPoolPotsdamProvider,
}
```
and
```py
HANDLER_REGISTRY = {
    "O2ARegistrySearchHandler": O2ARegistrySearchHandler,
    "SensorManagentSystemHandler": SensorManagentSystemHandler,
    "GeophysicalInstrumentPoolPotsdamHandler": GeophysicalInstrumentPoolPotsdamHandler,
}
```

**Comment by hafu** [comment]
Thank you for pointing out. I add your suggestions in #2
